# Generated by Django 4.0.5 on 2022-08-10 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('balance', models.IntegerField()),
                ('previousBalance', models.IntegerField()),
                ('read', models.BooleanField(default=False)),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('userCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory', models.TextField()),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('parentCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentCategory', to='budgetApp.categories')),
                ('userSubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSubCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.TextField(blank=True)),
                ('amount', models.IntegerField()),
                ('previousAccountBalance', models.IntegerField()),
                ('descriptionTransaction', models.TextField(blank=True)),
                ('transactionDate', models.DateTimeField(blank=True)),
                ('readTransaction', models.BooleanField(default=False)),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('accountNameTransaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountNameTransaction', to='budgetApp.account')),
                ('accountNameTransferFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountNameTransferFrom', to='budgetApp.account')),
                ('accountNameTransferTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountNameTransferTo', to='budgetApp.account')),
                ('categoryTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoryTransaction', to='budgetApp.categories')),
                ('subCategoryTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subCategoryTransaction', to='budgetApp.subcategories')),
                ('userTransaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTransaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
