# Generated by Django 4.0.5 on 2022-09-27 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('balance', models.IntegerField()),
                ('previousBalance', models.IntegerField()),
                ('read', models.BooleanField(default=False)),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('userCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory', models.TextField()),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('parentCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentCategory', to='budgetApp.categories')),
                ('userSubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSubCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionFromId', models.IntegerField(blank=True, null=True)),
                ('transactionType', models.TextField(blank=True)),
                ('amount', models.IntegerField()),
                ('previousAccountBalance', models.IntegerField()),
                ('currentAccountBalance', models.IntegerField()),
                ('descriptionTransaction', models.TextField(blank=True)),
                ('scheduleId', models.IntegerField(blank=True, null=True)),
                ('transactionDate', models.DateTimeField(blank=True)),
                ('readTransaction', models.BooleanField(default=False)),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('accountNameTransaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountNameTransaction', to='budgetApp.account')),
                ('accountNameTransferFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountNameTransferFrom', to='budgetApp.account')),
                ('accountNameTransferTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountNameTransferTo', to='budgetApp.account')),
                ('categoryTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoryTransaction', to='budgetApp.categories')),
                ('subCategoryTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subCategoryTransaction', to='budgetApp.subcategories')),
                ('userTransaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTransaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleFromId', models.IntegerField(blank=True, null=True)),
                ('scheduleType', models.TextField(blank=True)),
                ('amount', models.IntegerField()),
                ('previousScheduleAccountBalance', models.IntegerField()),
                ('currentScheduleAccountBalance', models.IntegerField()),
                ('descriptionSchedule', models.TextField(blank=True)),
                ('transactionId', models.IntegerField(blank=True, null=True)),
                ('startScheduleDate', models.DateTimeField(blank=True)),
                ('nextScheduleDate', models.DateTimeField(blank=True)),
                ('nextScheduleDateText', models.TextField(blank=True)),
                ('endScheduleDate', models.DateTimeField(blank=True)),
                ('endedSchedule', models.BooleanField(default=False)),
                ('neverEndSchedule', models.BooleanField(default=False)),
                ('repeatSchedule', models.BooleanField(default=False)),
                ('periodCountSchedule', models.IntegerField(blank=True, null=True)),
                ('periodProcessSchedule', models.IntegerField(blank=True, null=True)),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('accountNameSchedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountNameSchedule', to='budgetApp.account')),
                ('accountNameScheduleTransferFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountNameScheduleTransferFrom', to='budgetApp.account')),
                ('accountNameScheduleTransferTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountNameScheduleTransferTo', to='budgetApp.account')),
                ('categorySchedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorySchedule', to='budgetApp.categories')),
                ('subCategorySchedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subCategorySchedule', to='budgetApp.subcategories')),
                ('userSchedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSchedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(blank=True)),
                ('amount', models.IntegerField()),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('accountNameReport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountNameReport', to='budgetApp.account')),
                ('userReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetName', models.TextField()),
                ('currentAmount', models.IntegerField()),
                ('budgetAmount', models.IntegerField()),
                ('descriptionBudget', models.TextField(blank=True)),
                ('startDate', models.DateTimeField(blank=True)),
                ('endDate', models.DateTimeField(blank=True)),
                ('periodCount', models.IntegerField()),
                ('periodProcess', models.IntegerField()),
                ('minusAmount', models.BooleanField(default=False)),
                ('ins_date', models.DateTimeField(auto_now_add=True)),
                ('accountNameBudget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountNameBudget', to='budgetApp.account')),
                ('categoryBudget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoryBudget', to='budgetApp.categories')),
                ('subCategoryBudget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subCategoryBudget', to='budgetApp.subcategories')),
                ('userBudget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userBudget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
