# Generated by Django 4.0.5 on 2022-12-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0002_account_categories_subcategories_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='accountNameBudget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountNameBudget', to='budgetApp.account'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='categoryBudget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryBudget', to='budgetApp.categories'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='subCategoryBudget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCategoryBudget', to='budgetApp.subcategories'),
        ),
        migrations.AlterField(
            model_name='report',
            name='accountNameReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountNameReport', to='budgetApp.account'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='accountNameSchedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountNameSchedule', to='budgetApp.account'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='accountNameScheduleTransferFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountNameScheduleTransferFrom', to='budgetApp.account'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='accountNameScheduleTransferTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountNameScheduleTransferTo', to='budgetApp.account'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='categorySchedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorySchedule', to='budgetApp.categories'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subCategorySchedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCategorySchedule', to='budgetApp.subcategories'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accountNameTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountNameTransaction', to='budgetApp.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accountNameTransferFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountNameTransferFrom', to='budgetApp.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accountNameTransferTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountNameTransferTo', to='budgetApp.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='categoryTransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryTransaction', to='budgetApp.categories'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subCategoryTransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCategoryTransaction', to='budgetApp.subcategories'),
        ),
    ]
